INSERT INTO CONCORRENTE (NOME, CPF) VALUES ('rafael', '1521515875');
INSERT INTO CONCORRENTE (NOME, CPF) VALUES ('Pedro', '12345678910');
INSERT INTO CONCORRENTE (NOME, CPF) VALUES ('Maria', '9876543210');
INSERT INTO CONCORRENTE (NOME, CPF) VALUES ('João', '216543210');
INSERT INTO CONCORRENTE (NOME, CPF) VALUES ('Badunga', '12346878');


INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('sapatos', 50.00, true);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('CARRO', 852.00, true);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('mOTO', 600.00, true);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('BOI', 120.00, true);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('cavalo', 100.00, false);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('trator', 300.00, false);

INSERT INTO LANCE (LEILAO_ID,CONCORRENTE_ID, VALOR) VALUES (1, 1, 100.0);
INSERT INTO LANCE (LEILAO_ID, CONCORRENTE_ID, VALOR) VALUES (2, 2, 150.0);
INSERT INTO LANCE (LEILAO_ID, CONCORRENTE_ID, VALOR) VALUES (3, 3, 200.0);
INSERT INTO LANCE (LEILAO_ID, CONCORRENTE_ID, VALOR) VALUES (4, 4, 250.0);
INSERT INTO LANCE (LEILAO_ID, CONCORRENTE_ID, VALOR) VALUES (5, 5, 300.0);
INSERT INTO LANCE (LEILAO_ID, CONCORRENTE_ID, VALOR) VALUES (2, 5, 1150.0);

