INSERT INTO CONCORRENTE (NOME, CPF) VALUES ('rafael', '1521515875');
INSERT INTO CONCORRENTE (NOME, CPF) VALUES ('Pedro', '12345678910');
INSERT INTO CONCORRENTE (NOME, CPF) VALUES ('Maria', '9876543210');
INSERT INTO CONCORRENTE (NOME, CPF) VALUES ('João', '216543210');


INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('sapatos', 50.00, true);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('CARRO', 852.00, true);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('mOTO', 600.00, true);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('BOI', 120.00, true);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('cavalo', 100.00, false);
INSERT INTO LEILAO (DESCRICAO, VALORMINIMO, status) VALUES ('trator', 300.00, false);

